@startuml
state s1 <<start>>
state s2 <<start>>
state e1 <<end>>
state e2 <<end>>
结算单启动: 按周期生产
结算单启动: 关键点：清算周期（开始/结束）时间
结算单启动: 关键点：结算开始时间

s1 -> 交易完成
s2 -> 结算单启动

state 清算 {
	binlog -> 清算流水
	binlog: !逐笔处理!
	清算流水 -> 清算_净额_and_手续费
	清算_净额_and_手续费: clearing_bill 清算明细单
	清算_净额_and_手续费 -> 动账处理
	state 动账处理 {
		净额记账 --> 手续费记账
		净额记账: 待清算 to 待结算
		手续费记账: 无需记账，只需汇总
	}
	动账处理 -> 交易汇总
	交易汇总 -> 净额汇总
	净额汇总 -> 手续费汇总
}

state 结算 {
	结算单_汇总详情单 -> 汇总
	结算单_汇总详情单: 按最小计量周期生成结算单
	结算单_汇总详情单: 目前是天，可以扩展到小时
	state 汇总 {
		结算净额记账 --> 已处置手续费检查
		结算净额记账: 待结算户 to 商户余额户
		已处置手续费检查: 1. 已经从结算额扣除
		已处置手续费检查: 2. 已经从外部账户扣除（外扣）
		已处置手续费检查 --> 未处理手续费处置
		未处理手续费处置: 待结算户 to 平台手续费收入户
	}
	汇总 -> 税费处置
	税费处置: 根据手续费计税
	税费处置 -> 网关费处理
}

交易完成 -> binlog
结算单启动 -> 结算单_汇总详情单

交易汇总 --> 结算单_汇总详情单
净额汇总 --> 结算单_汇总详情单
手续费汇总 --> 结算单_汇总详情单

手续费汇总 -> 清算完成
网关费处理 -> 结算完成

清算完成 -> e1
结算完成 -> e2
@enduml